### ISSUE TITLE
Exception during interpreter shutdown

### ISSUE THREAD

**Issue by andresriancho** [noxdafox/pebble#14]
This issue is something I found while running unittests in my build environment. It seems like an exception during interpreter shutdown:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.3/local/lib/python2.7/site-packages/pebble/pool/process.py", line 170, in message_manager_loop
    pool_manager.process_next_message(SLEEP_UNIT)
  File "/home/ubuntu/virtualenvs/venv-2.7.3/local/lib/python2.7/site-packages/pebble/pool/process.py", line 199, in process_next_message
    message = self.worker_manager.receive(timeout)
  File "/home/ubuntu/virtualenvs/venv-2.7.3/local/lib/python2.7/site-packages/pebble/pool/process.py", line 322, in receive
    return NoMessage()
TypeError: 'NoneType' object is not callable
```

Not sure if this is related to a) me not calling `stop()`, `terminate()`, etc. on the pool or a real bug in the `pebble` code. Thoughts?

**Comment by andresriancho** [comment]
Another similar error which is found when my test runner (nosetests) finishes running the tests and is finishing:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.3/local/lib/python2.7/site-packages/pebble/pool/process.py", line 170, in message_manager_loop
    pool_manager.process_next_message(SLEEP_UNIT)
  File "/home/ubuntu/virtualenvs/venv-2.7.3/local/lib/python2.7/site-packages/pebble/pool/process.py", line 199, in process_next_message
    message = self.worker_manager.receive(timeout)
  File "/home/ubuntu/virtualenvs/venv-2.7.3/local/lib/python2.7/site-packages/pebble/pool/process.py", line 320, in receive
    return self.pool_channel.recv()
  File "/home/ubuntu/virtualenvs/venv-2.7.3/local/lib/python2.7/site-packages/pebble/pool/channel.py", line 52, in recv
    return self.reader.recv()
EOFError
```

**Comment by noxdafox** [comment]
The first error is a common issue you get when a thread (the `Pool` uses threads internally for maintenance routine) is terminated abruptly by the interpreter. This is probably due to the fact you're not calling `Pool.join` which is highly recommended as, when not doing so, you might leak processes if your application keeps going.

I'd recommend you to call either `close` or `stop` and then `join` the `Pool`. The [documentation](pythonhosted.org/Pebble/) explain the difference between the methods.

The second issue is related but has a slightly different nature, it's due to one of the `worker` processes being terminated abruptly.

Both issues are harmless if triggering at shutdown. Still it's always better to call `join`.

**Comment by andresriancho** [comment]
Awesome, thanks! Added the call to join()
