### ISSUE TITLE
I got error when use pool

### ISSUE THREAD

**Issue by mgxian** [noxdafox/pebble#20]
my code
```
def task_done(iterator):
    while True:
        try:
            result = next(iterator)
        except StopIteration:
            break
        except TimeoutError as error:
            print("function took longer than %d seconds" % error.args[1])
        except ProcessExpired as error:
            print("%s. Exit code: %d" % (error, error.exitcode))
        except Exception as error:
            print("function raised %s" % error)
            traceback.print_exc()  # Python's traceback of remote process


with ProcessPool(max_workers=PROCESS_POOL_SIZE, max_tasks=10) as pool:
       future = pool.map(crawl_func, summoners, timeout=0)
       iterator = future.result()
       task_done(iterator)
```

errors
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python27\Lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "c:\python27\Lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "c:\python27\Lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "c:\python27\Lib\pickle.py", line 886, in load_eof
    raise EOFError
EOFError
```

python2.7 on win10  please help me

**Comment by noxdafox** [comment]
Please provide a working example which shows this behaviour so I can test it. 

It must not be your entire program but the bare minimum amount of code which once executed leads to the issue.

Note to self: look into https://github.com/LibraryOfCongress/bagit-python/issues/42

**Comment by noxdafox** [comment]
Hello,

I did not manage to reproduce the error with the above code. Is this issue still relevant?
