### ISSUE TITLE
Error upgrading Pebble to 4.4.1 on Windows

### ISSUE THREAD

**Issue by JimmyCarlos** [noxdafox/pebble#51]
Hi,

I'm currently running Pebble 4.4.0 and to get the updated pebble I typed "pip install pebble --upgrade" into a cmd.exe with admin privileges. I got an error, which I have written below.

```python
C:\Windows>pip install pebble --upgrade
Collecting pebble
  Using cached https://files.pythonhosted.org/packages/5e/a3/16f98c868854a6916d68bb6ea02edcf7c91021ad41892862f1307c6831df/Pebble-4.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jjsag\AppData\Local\Temp\pip-build-cgvge9xr\pebble\setup.py", line 39, in <module>
        version="{}".format(package_version()),
      File "C:\Users\jjsag\AppData\Local\Temp\pip-build-cgvge9xr\pebble\setup.py", line 14, in package_version
        version = read_version(version_path)
      File "C:\Users\jjsag\AppData\Local\Temp\pip-build-cgvge9xr\pebble\setup.py", line 22, in read_version
        return subprocess.check_output(('git', 'describe')).rstrip().decode()
      File "c:\users\jjsag\appdata\local\programs\thonny\lib\subprocess.py", line 316, in check_output
        **kwargs).stdout
      File "c:\users\jjsag\appdata\local\programs\thonny\lib\subprocess.py", line 383, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\users\jjsag\appdata\local\programs\thonny\lib\subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "c:\users\jjsag\appdata\local\programs\thonny\lib\subprocess.py", line 955, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    ----------------------------------------`

I see thonny is in the stack near the bottom, it is my IDE I use to help me with my python, but it has had no issues with any other modules before.

Thanks for reading this, and any suggestions for help will be appreciated.

**Comment by noxdafox** [comment]
It is due to `git` missing from your environment. This should be handled by the `setup` script but Python 3 changed the exception type from `CalledProcessError` to `FileNotFoundError`.

Fix is coming.

**Comment by noxdafox** [comment]
Release `4.5.0` should address this issue. Please re-open this ticket if not.
