### ISSUE TITLE
error while trying to pass a generator to pool map

### ISSUE THREAD

**Issue by marinsdh** [noxdafox/pebble#89]
Hello, i' having a function that needs to have multiple args passed:

```
def download_report_by_account(
    api_client, report_name, query, customer_id, date
):
   #do stuff
```

this is the function that yields the args to be passed:

```
    def process_args_generator():
        for day in range(int(days_to_back_fill)):
            date = (
                    datetime.strptime(dag_execution_date, "%Y-%m-%d") - timedelta(days=day)
            ).strftime("%Y-%m-%d")
            report_gaql_query = report_gaql_query.replace(
                "start_date", f"'{date}'"
            ).replace("end_date", f"'{date}'")

            for account in managed_accounts:
                yield [
                    api_client,
                    report_name,
                    report_gaql_query,
                    account["account_id"],
                    date,
                ]
```

and this is the way in which I'm building the pool:

```
with ProcessPool(max_workers=process_pool_size) as pool:
            future = pool.map(download_report_by_account, [process_args_generator], timeout=5)

            iterator = future.result()

            while True:
                try:
                    result = next(iterator)
                except StopIteration:
                    break
                except TimeoutError as error:
                    print("function took longer than %d seconds" % error.args[1])
                except ProcessExpired as error:
                    print("%s. Exit code: %d" % (error, error.exitcode))
                except Exception as error:
                    print("function raised %s" % error)
                    print(error.traceback)  # Python's traceback of remote process
```

somehow I get this error:

```
Traceback (most recent call last):
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -     self.run()
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -     self._target(*self._args, **self._kwargs)
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -   File "/tmp/venv8ljblurt/lib/python3.8/site-packages/pebble/pool/process.py", line 167, in task_scheduler_loop
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -     pool_manager.schedule(task)
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -   File "/tmp/venv8ljblurt/lib/python3.8/site-packages/pebble/pool/process.py", line 217, in schedule
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -     self.worker_manager.dispatch(task)
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -   File "/tmp/venv8ljblurt/lib/python3.8/site-packages/pebble/pool/process.py", line 347, in dispatch
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -     self.pool_channel.send(WorkerTask(task.id, task.payload))
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -   File "/tmp/venv8ljblurt/lib/python3.8/site-packages/pebble/pool/channel.py", line 76, in send
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -     return self.writer.send(obj)
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -   File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 206, in send
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -     self._send_bytes(_ForkingPickler.dumps(obj))
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -   File "/usr/local/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO -     cls(buf, protocol).dump(obj)
[2022-01-11, 09:37:20 UTC] {{process_utils.py:143}} INFO - AttributeError: Can't pickle local object 'get_report.<locals>.process_args_generator'
```

any insights or suggestions on how to make this work? :)

**Comment by noxdafox** [comment]
Please use stackoverflow for these kinds of questions. GH issues is to report actual bugs or feature requests and not for asking guidance.

In your specific case, you are passing a list of 1 element with a function within: `[process_args_generator]`. This function cannot be pickled and sent to the process. Hence, you get the `Can't pickle` error.

You must puss the generator to the `map` itself: `pool.map(download_report_by_account, process_args_generator(), timeout=5)`.
